export const traders = [
  {
    id: 1,
    name: "Bigdream99",
    avatar: "/trader1.png",
    earnings: "₦5000",
    rating: 4,
    status: "premium",
  },
  {
    id: 2,
    name: "Ollikeyz",
    avatar: "/bustling-stock-exchange.png",
    earnings: "Free",
    rating: 3,
    status: "free",
  },
  {
    id: 3,
    name: "DebbyForex",
    avatar: "/trader3.png",
    earnings: "₦5000",
    rating: 4,
    status: "premium",
  },
  {
    id: 4,
    name: "PipsMaster",
    avatar: "/trader4.png",
    earnings: "₦7500",
    rating: 5,
    status: "premium",
  },
  {
    id: 5,
    name: "FxQueen",
    avatar: "/trader5.png",
    earnings: "₦2000",
    rating: 3,
    status: "free",
  },
  {
    id: 6,
    name: "CryptoKing",
    avatar: "/trader6.png",
    earnings: "₦12000",
    rating: 5,
    status: "premium",
  },
  {
    id: 7,
    name: "TradeGuru",
    avatar: "/trader7.png",
    earnings: "₦4500",
    rating: 4,
    status: "premium",
  },
  {
    id: 8,
    name: "MarketBoss",
    avatar: "/trader8.png",
    earnings: "₦3000",
    rating: 3,
    status: "free",
  },
  {
    id: 9,
    name: "GoldenPips",
    avatar: "/trader9.png",
    earnings: "₦8600",
    rating: 5,
    status: "premium",
  },
  {
    id: 10,
    name: "StarTrader",
    avatar: "/trader10.png",
    earnings: "₦1500",
    rating: 2,
    status: "free",
  },
  {
    id: 11,
    name: "PipHunter",
    avatar: "/trader11.png",
    earnings: "₦6700",
    rating: 4,
    status: "premium",
  },
  {
    id: 12,
    name: "ForexWizard",
    avatar: "/trader12.png",
    earnings: "₦9200",
    rating: 5,
    status: "premium",
  },
  {
    id: 13,
    name: "ScalpQueen",
    avatar: "/trader13.png",
    earnings: "₦2500",
    rating: 3,
    status: "free",
  },
  {
    id: 14,
    name: "LongShot",
    avatar: "/trader14.png",
    earnings: "₦11000",
    rating: 5,
    status: "premium",
  },
  {
    id: 15,
    name: "RiskTaker",
    avatar: "/trader15.png",
    earnings: "₦1000",
    rating: 2,
    status: "free",
  },
];
