export const traders = [
  {
    id: 1,
    name: "Bigdream99",
    avatar: "/trader1.png",
    earnings: "₦5000",
    rating: 4,
    status: "premium",
  },
  {
    id: 2,
    name: "Ollikeyz",
    avatar: "/bustling-stock-exchange.png",
    earnings: "Free",
    rating: 3,
    status: "free",
  },
  {
    id: 3,
    name: "DebbyForex",
    avatar: "/trader3.png",
    earnings: "₦5000",
    rating: 4,
    status: "premium",
  },
  {
    id: 4,
    name: "PipsMaster",
    avatar: "/trader4.png",
    earnings: "₦7500",
    rating: 5,
    status: "premium",
  },
  {
    id: 5,
    name: "FxQueen",
    avatar: "/trader5.png",
    earnings: "₦2000",
    rating: 3,
    status: "free",
  },
  {
    id: 6,
    name: "CryptoKing",
    avatar: "/trader6.png",
    earnings: "₦12000",
    rating: 5,
    status: "premium",
  },
];